version: 1.0.{build}
skip_tags: true
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: v7h9p7gDilhyGpr7m50dmxp8Kvcasz0vB
before_build:
  - nuget restore PokerBot.sln"
build:
  project: .\PokerBot.sln
  verbosity: minimal
test_script:
- ps: >-
    ./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe -register:user -target:./packages/xunit.runner.console.2.1.0/tools/xunit.console.exe "-targetargs:""./PokerBotUnitTests/bin/Debug/Nicomputer.PokerBot.UnitTests.dll"" -noshadow -appveyor -parallel none -xml results.xml" -filter:"+[Nicomputer.PokerBot.*]*" -output:opencoverCoverage.xml
